language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

services:
  - mongodb
  - redis-server

before_script:
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 4 ]; then sed -i 1d "tests/config/php.ini"; fi;'
  - phpenv config-add tests/config/php.ini
  - php -m
  - php -i
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --prefer-source --no-interaction
  - pecl install redis
  - mysql -e 'CREATE DATABASE IF NOT EXISTS widget_tests;'
  - psql -c 'CREATE DATABASE widget_tests;' -U postgres
  - mkdir -p build/logs
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 3 ]; then php -S 0.0.0.0:8000 -t tests/WidgetTest/Fixtures/; fi;' > /dev/null &

script:
  - phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v --exclude-no-stmt