language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mongodb
  - memcached
  - redis-server

before_script:
  - composer install --prefer-source --no-interaction
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -ge 5 ]; then printf "\n" | pecl install apcu-4.0.10; fi;'
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 4 ]; then sed -i 1d "tests/config/php.ini"; fi;'
  - sh -c 'if [ $(php -r "echo (int) defined(\"HHVM_VERSION\");") -eq 0 ]; then phpenv config-add tests/config/php.ini; fi;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wei_tests;'
  - psql -c 'CREATE DATABASE wei_tests;' -U postgres
  - mkdir -p build/logs
  - sh -c 'if [ $(php -r "echo PHP_MINOR_VERSION;") -gt 3 ]; then php -S 0.0.0.0:8000 -t tests/unit/Fixtures/; fi;' > /dev/null &

script:
  - ./vendor/bin/phpunit tests/unit/RedisTest.php --verbose --stderr --coverage-clover build/logs/clover.xml

after_script:
  - pkill php
  - php vendor/bin/coveralls -v --exclude-no-stmt

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
